version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/nerv
    overwrite: yes
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStart:
    - location: deploy/start.sh
      timeout: 300
      runas: ubuntu 
  ValidateService:
    - location: deploy/MonitorService.sh
      timeout: 30
      runas: ubuntu